import { describe, expect, it } from "vitest";
import type { CreateOrderInput } from "./create.js";
import { createOrder } from "./create.js";
import { transition } from "./machine.js";
import type { DeadlineKind, Order, OrderEvent, OrderPolicy, Price } from "./model.js";
import { isOpen, modeOf, ORDER_EVENT_KINDS, ORDER_STATES } from "./model.js";
import { moneyInvariantViolations } from "./money.js";
import { ORDER_OUTCOMES, outcomeFor } from "./outcome.js";

/**
 * A long walk over the machine, driven by a generator that is random enough to
 * find pairings a person would not write down and completely reproducible from
 * its seed. There is no real randomness anywhere in this package: a failure
 * here has to be reproducible from the seed printed in the message, or it is
 * not a finding, it is a rumour.
 *
 * What the walk checks at every single step is the money — in the order and in
 * the effects both. The gateway will feed this machine events off a queue that
 * delivers at least once, in an order nobody chose, and the promise is that no
 * sequence of them can put an order into a state where somebody's money is
 * gone with nothing recording it, nor ask the gateway to spend that money or
 * hand over the goods twice.
 *
 * The effects half of that is not optional. Money moves through effects, so a
 * walk that only looked at the order would be blind to the double charge and
 * the double fulfillment, which are the two mistakes a buyer would notice
 * first.
 */

/**
 * A small deterministic generator. Seeded, integer-only, no clock.
 *
 * The seed is mixed and the state stirred a few times before anything is
 * handed out. Without that, small seeds spend their first outputs down near
 * zero and every walk starts with the same choice — which is how the first
 * version of this file managed to test one fulfillment mode two hundred times
 * over and call it coverage.
 */
function generator(seed: number): () => number {
  let state = (Math.imul(seed >>> 0, 2_654_435_761) ^ 0x9e37_79b9) >>> 0;

  const step = (): number => {
    state = (state ^ (state << 13)) >>> 0;
    state = (state ^ (state >>> 17)) >>> 0;
    state = (state ^ (state << 5)) >>> 0;
    return state / 0x1_0000_0000;
  };

  for (let i = 0; i < 8; i += 1) step();
  return step;
}

function pick<T>(next: () => number, items: readonly T[]): T {
  const item = items[Math.floor(next() * items.length)];
  if (item === undefined) throw new Error("the generator ran off the end of the list");
  return item;
}

/**
 * The walk's clock moves five seconds a step, so these deadlines are short
 * enough that a walk actually runs past them and expiries are real choices
 * rather than events that are always refused as not yet due. They are test
 * values and say nothing about the pilot's numbers.
 */
const POLICY: OrderPolicy = {
  deadlines: {
    quoteTtlMs: 10_000,
    settleResponseMs: 25_000,
    syncResponseMs: 8_000,
    paymentAfterConfirmationMs: 12_000,
    confirmationResponseMs: 15_000,
    asyncFulfillmentMs: 20_000,
  },
  redelivery: { baseDelayMs: 500, factor: 3, maxDelayMs: 20_000, maxAttempts: 4 },
};

const PRICE: Price = { amount: "12.00", currency: "USD", asOf: 500_000 };

const DEADLINES: readonly DeadlineKind[] = [
  "quote_expiry",
  "settle_response",
  "confirmation_response",
  "payment_after_confirmation",
  "sync_response",
  "async_fulfillment",
];

/** Every shape each event can arrive in, so the walk can choose among them. */
function everyEvent(at: number): readonly OrderEvent[] {
  return ORDER_EVENT_KINDS.flatMap((kind): OrderEvent[] => {
    switch (kind) {
      case "quote_answered":
        return [
          { kind, at, available: true, price: PRICE },
          { kind, at, available: false },
        ];
      case "handler_refused":
      case "refuse_called":
        return ["out_of_stock", "invalid_params", "cannot_fulfill"].map((code) => ({
          kind,
          at,
          code,
          message: "generated by the walk",
        }));
      case "payment_verification_failed":
        return (["signature", "insufficient_funds", "price_stale"] as const).map((reason) => ({
          kind,
          at,
          reason,
        }));
      case "deadline_expired":
        return DEADLINES.map((deadline) => ({ kind, at, deadline }));
      default:
        return [{ kind, at }];
    }
  });
}

/**
 * The next event of the walk, chosen out of three pools in order of
 * preference.
 *
 * Most of the time it is an event that both moves the order and leaves it
 * open. An order dies easily — a refusal or a departure ends it from almost
 * anywhere — and a walk that took those as readily as anything else would
 * spend its life in the first three states and call that coverage. Next in
 * preference is anything that moves the order at all, which is what closes it.
 * And a fifth of the time it is any event whatsoever, which is what turns up
 * the pairings nobody would have thought to write down.
 *
 * "Moves the order" means the machine changed something, not merely that the
 * name of the state changed: the settle of a purchase whose money moves first
 * leaves the order in `quoted`, and a walk that only chased new state names
 * would never get past it.
 */
function anEvent(next: () => number, order: Order, at: number): OrderEvent {
  const all = everyEvent(at);
  const advancing = all.filter((event) => {
    const result = transition(order, event);
    return result.ok && result.order !== order;
  });
  const keepsItOpen = advancing.filter((event) => {
    const result = transition(order, event);
    return result.ok && isOpen(result.order.state);
  });

  const die = next();
  if (die < 0.6 && keepsItOpen.length > 0) return pick(next, keepsItOpen);
  if (die < 0.8 && advancing.length > 0) return pick(next, advancing);
  return pick(next, all);
}

type Step = { readonly event: string; readonly accepted: boolean; readonly after: string };

function takeAWalk(seed: number, steps: number): { order: Order; trace: readonly Step[] } {
  const next = generator(seed);
  const input: CreateOrderInput = {
    id: `ord_walk_${seed}`,
    at: 500_000,
    mode: modeOf(pick(next, ["sync", "async", "confirm"])),
    policy: POLICY,
    priceCheck: pick(next, ["none", "merchant"]),
    cardPrice: PRICE,
    test: false,
    selling: "open",
  };

  const created = createOrder(input);
  if (!created.ok) throw new Error(`seed ${seed} could not create an order`);

  let order = created.order;
  const trace: Step[] = [];

  for (let step = 0; step < steps; step += 1) {
    const event = anEvent(next, order, 500_000 + step * 5_000);
    const result = transition(order, event);
    if (result.ok) order = result.order;
    trace.push({
      event: event.kind,
      accepted: result.ok,
      after: `${order.state}/${order.payment}`,
    });
  }

  return { order, trace };
}

describe("a long walk over the machine", () => {
  const seeds = [1, 7, 42, 1_337, 20_260_826, 999_983];

  for (const seed of seeds) {
    it(`keeps the money invariants over two hundred steps from seed ${seed}`, () => {
      const next = generator(seed);
      const input: CreateOrderInput = {
        id: `ord_walk_${seed}`,
        at: 500_000,
        mode: modeOf(pick(next, ["sync", "async", "confirm"])),
        policy: POLICY,
        priceCheck: pick(next, ["none", "merchant"]),
        cardPrice: PRICE,
        test: false,
        selling: "open",
      };
      const created = createOrder(input);
      expect(created.ok).toBe(true);
      if (!created.ok) return;

      let order = created.order;
      // What the gateway would have been told to do, so far.
      let chargesInFlight = 0;
      let goodsReleased = 0;
      let receipts = 0;
      let accepted = 0;

      for (let step = 0; step < 200; step += 1) {
        const event = anEvent(next, order, 500_000 + step * 5_000);
        const result = transition(order, event);
        if (!result.ok) continue;

        accepted += 1;
        order = result.order;
        const where = `seed ${seed}, step ${step}, ${event.kind} -> ${order.state}/${order.payment}`;

        expect(moneyInvariantViolations(order), where).toStrictEqual([]);
        expect(ORDER_STATES, where).toContain(order.state);
        expect(ORDER_OUTCOMES, where).toContain(outcomeFor(order));

        for (const effect of result.effects) {
          if (effect.kind === "execute_payment") chargesInFlight += 1;
          if (effect.kind === "release_goods_to_agent") goodsReleased += 1;
          if (effect.kind === "issue_receipt") receipts += 1;
          if (effect.kind === "mark_refund_due") {
            // A debt is a claim that the buyer's money is with the merchant.
            expect(order.payment, `${where}: a refund marked without a charge`).toBe("settled");
          }
        }
        if (event.kind === "payment_settled" || event.kind === "payment_settle_failed") {
          chargesInFlight -= 1;
        }

        // The buyer's money is sent for execution once at a time, and one
        // order hands over its goods and writes its receipt exactly once.
        expect(chargesInFlight, `${where}: charges in flight`).toBeLessThanOrEqual(1);
        expect(goodsReleased, `${where}: the goods went out twice`).toBeLessThanOrEqual(1);
        expect(receipts, `${where}: two receipts for one order`).toBeLessThanOrEqual(1);
      }

      // A floor under the loop: a machine that refused everything would sail
      // through every check above.
      expect(accepted, `seed ${seed}`).toBeGreaterThan(3);
    });
  }

  it("produces the very same walk from the very same seed", () => {
    // Determinism is not a nicety here: an order is replayed from its events
    // when the gateway restarts, and a machine that answered differently on
    // the replay would hand a buyer a different outcome than the one he saw.
    const first = takeAWalk(20_260_826, 120);
    const second = takeAWalk(20_260_826, 120);

    expect(second.trace).toStrictEqual(first.trace);
    expect(second.order).toStrictEqual(first.order);
  });

  it("produces different walks from different seeds", () => {
    // The negative control for the test above: if every seed produced the same
    // walk, "the same seed gives the same walk" would be proving nothing.
    const one = takeAWalk(1, 120);
    const other = takeAWalk(42, 120);

    expect(other.trace).not.toStrictEqual(one.trace);
  });

  it("answers the same question the same way twice in a row", () => {
    const { order } = takeAWalk(7, 30);
    const event: OrderEvent = { kind: "deliver_called", at: 900_000 };

    expect(transition(order, event)).toStrictEqual(transition(order, event));
  });

  it("visits every state of the machine for the walk to mean anything", () => {
    // A walk that never left `created` would pass every check above while
    // testing nothing at all. A single order's life is short — most of these
    // walks fall into a closed state early — so the coverage is counted over
    // two hundred orders rather than over one.
    const visited = new Set<string>();
    for (let seed = 1; seed <= 400; seed += 1) {
      const walked = takeAWalk(seed, 200);
      for (const step of walked.trace) {
        visited.add(step.after.split("/")[0] ?? "");
      }
      expect(moneyInvariantViolations(walked.order), `seed ${seed}`).toStrictEqual([]);
    }

    expect([...visited].sort()).toStrictEqual([...ORDER_STATES].sort());
  });
});
