import { describe, expect, it } from "vitest";
import type { CreateOrderInput } from "./create.js";
import { createOrder } from "./create.js";
import { deadlines } from "./deadlines.js";
import { transition } from "./machine.js";
import type { DeadlineKind, Effect, Order, OrderEvent, OrderPolicy, Price } from "./model.js";
import { isOpen, modeOf, ORDER_EVENT_KINDS, ORDER_STATES } from "./model.js";
import { moneyInvariantViolations } from "./money.js";
import { ORDER_OUTCOMES, outcomeFor } from "./outcome.js";

/**
 * A long walk over the machine, driven by a generator that is random enough to
 * find pairings a person would not write down and completely reproducible from
 * its seed. There is no real randomness anywhere in this package: a failure
 * here has to be reproducible from the seed printed in the message, or it is
 * not a finding, it is a rumour.
 *
 * What the walk checks at every single step is the money — in the order and in
 * the effects both. The gateway will feed this machine events off a queue that
 * delivers at least once, in an order nobody chose, and the promise is that no
 * sequence of them can put an order into a state where somebody's money is
 * gone with nothing recording it, nor ask the gateway to spend that money or
 * hand over the goods twice.
 *
 * The effects half of that is not optional. Money moves through effects, so a
 * walk that only looked at the order would be blind to the double charge and
 * the double fulfillment, which are the two mistakes a buyer would notice
 * first.
 */

/**
 * A small deterministic generator. Seeded, integer-only, no clock.
 *
 * The seed is mixed and the state stirred a few times before anything is
 * handed out. Without that, small seeds spend their first outputs down near
 * zero and every walk starts with the same choice — which is how the first
 * version of this file managed to test one fulfillment mode two hundred times
 * over and call it coverage.
 */
function generator(seed: number): () => number {
  let state = (Math.imul(seed >>> 0, 2_654_435_761) ^ 0x9e37_79b9) >>> 0;

  const step = (): number => {
    state = (state ^ (state << 13)) >>> 0;
    state = (state ^ (state >>> 17)) >>> 0;
    state = (state ^ (state << 5)) >>> 0;
    return state / 0x1_0000_0000;
  };

  for (let i = 0; i < 8; i += 1) step();
  return step;
}

function pick<T>(next: () => number, items: readonly T[]): T {
  const item = items[Math.floor(next() * items.length)];
  if (item === undefined) throw new Error("the generator ran off the end of the list");
  return item;
}

const WALK_STARTS_AT = 500_000;

/**
 * How far the walk's clock moves between two events. Unevenly, and sometimes
 * by a lot — real time does not arrive in equal ticks either, and a walk whose
 * clock crept forward at a fixed rate could never leave a wait standing long
 * enough for it to come due. Every deadline in the policy below fits inside
 * the longest of these jumps.
 */
function tick(next: () => number, at: number): number {
  return at + 1_000 + Math.floor(next() * 4) * 10_000;
}

/**
 * Short enough that a walk of a couple of hundred steps runs past all of them
 * and every expiry is a real choice rather than an event that is always
 * refused as not yet due. They are test values and say nothing about the
 * pilot's numbers.
 */
const POLICY: OrderPolicy = {
  deadlines: {
    quoteResponseMs: 6_000,
    quoteTtlMs: 10_000,
    settleResponseMs: 25_000,
    syncResponseMs: 8_000,
    paymentAfterConfirmationMs: 12_000,
    confirmationResponseMs: 15_000,
    asyncFulfillmentMs: 20_000,
  },
  redelivery: { baseDelayMs: 500, factor: 3, maxDelayMs: 20_000, maxAttempts: 4 },
};

const PRICE: Price = { amount: "12.00", currency: "USD", asOf: 500_000 };

const DEADLINES: readonly DeadlineKind[] = [
  "quote_response",
  "quote_expiry",
  "settle_response",
  "confirmation_response",
  "payment_after_confirmation",
  "sync_response",
  "async_fulfillment",
];

/** Every shape each event can arrive in, so the walk can choose among them. */
function everyEvent(at: number): readonly OrderEvent[] {
  return ORDER_EVENT_KINDS.flatMap((kind): OrderEvent[] => {
    switch (kind) {
      case "quote_answered":
        return [
          { kind, at, available: true, price: PRICE },
          { kind, at, available: false },
        ];
      case "handler_refused":
      case "refuse_called":
        return ["out_of_stock", "invalid_params", "cannot_fulfill"].map((code) => ({
          kind,
          at,
          code,
          message: "generated by the walk",
        }));
      case "payment_verification_failed":
        return (["signature", "insufficient_funds", "price_stale"] as const).map((reason) => ({
          kind,
          at,
          reason,
        }));
      case "deadline_expired":
        return DEADLINES.map((deadline) => ({ kind, at, deadline }));
      default:
        return [{ kind, at }];
    }
  });
}

/**
 * The effects a walk has to reach if its effect checks are to mean anything:
 * money going out, goods going out, a debt being written down.
 */
const EFFECTS_WORTH_REACHING: readonly Effect["kind"][] = [
  "execute_payment",
  "release_goods_to_agent",
  "issue_receipt",
  "mark_refund_due",
];

/**
 * The next event of the walk, chosen out of five pools in order of preference,
 * each of which exists because the walk without it was measured to be blind to
 * something.
 *
 * Most of the time it is an event that both moves the order and leaves it
 * open: an order dies easily, and a walk that took a departure as readily as
 * anything else would spend its life in the first three states and call that
 * coverage. Some of the time it is one that spends money or hands goods over,
 * because those are what the effect checks are written about. Some of the time
 * it is a wait, because otherwise no clock in the machine is ever left running
 * long enough to come due. And a small share of the time it is any event
 * whatsoever, which is what turns up the pairings nobody would have thought to
 * write down.
 *
 * "Moves the order" means the machine changed something, not merely that the
 * name of the state changed: the settle of a purchase whose money moves first
 * leaves the order in `quoted`, and a walk that only chased new state names
 * would never get past it.
 */
function anEvent(next: () => number, order: Order, at: number): OrderEvent {
  const all = everyEvent(at);
  const advancing = all.filter((event) => {
    const result = transition(order, event);
    return result.ok && result.order !== order;
  });
  const keepsItOpen = advancing.filter((event) => {
    const result = transition(order, event);
    return result.ok && isOpen(result.order.state);
  });
  // Preferring events that keep an order alive is what gets the walk to the
  // far side of the machine, but on its own it starves exactly the paying and
  // closing events the effect checks below are written about — measured over
  // six seeds, the goods went out once and a debt was written once.
  const spendsOrHandsOver = advancing.filter((event) => {
    const result = transition(order, event);
    return (
      result.ok && result.effects.some((effect) => EFFECTS_WORTH_REACHING.includes(effect.kind))
    );
  });
  // And preferring those in turn starved every clock in the machine. In a
  // settling state the only events that move the order at all are the settle's
  // own two outcomes, so a walk that reaches for them takes them at once and
  // no deadline is ever left long enough to come due: measured, zero accepted
  // expiries across the seeds that carry the money assertions, and the
  // double-charge check those assertions are for could not be reached from any
  // of them. A walk that never lets time pass is only testing half the machine.
  const timeDriven = advancing.filter((event) => event.kind === "deadline_expired");
  // Waiting is a move too, and the only one that gets a deadline anywhere near
  // coming due. These are the events the machine will refuse: taking one costs
  // the order nothing and lets its clock run.
  const idles = all.filter((event) => !transition(order, event).ok);
  const waitingOnSomething = deadlines(order).length > 0;

  const die = next();
  if (die < 0.2 && timeDriven.length > 0) return pick(next, timeDriven);
  if (die < 0.4 && waitingOnSomething && idles.length > 0) return pick(next, idles);
  if (die < 0.6 && spendsOrHandsOver.length > 0) return pick(next, spendsOrHandsOver);
  if (die < 0.85 && keepsItOpen.length > 0) return pick(next, keepsItOpen);
  if (die < 0.93 && advancing.length > 0) return pick(next, advancing);
  return pick(next, all);
}

type Step = {
  readonly event: string;
  readonly accepted: boolean;
  readonly after: string;
  readonly effects: readonly string[];
};

function takeAWalk(seed: number, steps: number): { order: Order; trace: readonly Step[] } {
  const next = generator(seed);
  const input: CreateOrderInput = {
    id: `ord_walk_${seed}`,
    at: WALK_STARTS_AT,
    mode: modeOf(pick(next, ["sync", "async", "confirm"])),
    policy: POLICY,
    priceCheck: pick(next, ["none", "merchant"]),
    cardPrice: PRICE,
    test: false,
    selling: "open",
  };

  const created = createOrder(input);
  if (!created.ok) throw new Error(`seed ${seed} could not create an order`);

  let order = created.order;
  let at = WALK_STARTS_AT;
  const trace: Step[] = [];

  for (let step = 0; step < steps; step += 1) {
    at = tick(next, at);
    const event = anEvent(next, order, at);
    const result = transition(order, event);
    if (result.ok) order = result.order;
    trace.push({
      event: event.kind,
      accepted: result.ok,
      after: `${order.state}/${order.payment}`,
      effects: result.ok ? result.effects.map((effect) => effect.kind) : [],
    });
  }

  return { order, trace };
}

describe("a long walk over the machine", () => {
  /**
   * Three of these are here because they were measured to get somewhere the
   * others do not: 3 hands the goods over and writes a receipt, 8 and 10 write
   * a debt down. Without them the effect counters below run over walks that
   * never produce the effects they count, which is a check that cannot fail.
   */
  const seeds = [1, 3, 7, 8, 10, 42, 1_337, 20_260_826, 999_983];

  for (const seed of seeds) {
    it(`keeps the money invariants over two hundred steps from seed ${seed}`, () => {
      const next = generator(seed);
      const input: CreateOrderInput = {
        id: `ord_walk_${seed}`,
        at: WALK_STARTS_AT,
        mode: modeOf(pick(next, ["sync", "async", "confirm"])),
        policy: POLICY,
        priceCheck: pick(next, ["none", "merchant"]),
        cardPrice: PRICE,
        test: false,
        selling: "open",
      };
      const created = createOrder(input);
      expect(created.ok).toBe(true);
      if (!created.ok) return;

      let order = created.order;
      let at = WALK_STARTS_AT;
      // What the gateway would have been told to do, so far.
      let chargesInFlight = 0;
      let goodsReleased = 0;
      let receipts = 0;
      let accepted = 0;
      const reached = new Set<string>();

      for (let step = 0; step < 200; step += 1) {
        at = tick(next, at);
        const event = anEvent(next, order, at);
        const result = transition(order, event);
        if (!result.ok) continue;

        accepted += 1;
        order = result.order;
        const where = `seed ${seed}, step ${step}, ${event.kind} -> ${order.state}/${order.payment}`;

        expect(moneyInvariantViolations(order), where).toStrictEqual([]);
        expect(ORDER_STATES, where).toContain(order.state);
        expect(ORDER_OUTCOMES, where).toContain(outcomeFor(order));

        for (const effect of result.effects) {
          if (effect.kind === "execute_payment") chargesInFlight += 1;
          if (effect.kind === "release_goods_to_agent") goodsReleased += 1;
          if (effect.kind === "issue_receipt") receipts += 1;
          if (effect.kind === "mark_refund_due") {
            // A debt is a claim that the buyer's money is with the merchant.
            expect(order.payment, `${where}: a refund marked without a charge`).toBe("settled");
          }
          reached.add(effect.kind);
        }
        if (event.kind === "payment_settled" || event.kind === "payment_settle_failed") {
          chargesInFlight -= 1;
        }

        // The buyer's money is sent for execution once at a time, and one
        // order hands over its goods and writes its receipt exactly once. The
        // floor of nought matters as much as the ceiling of one: a counter
        // driven negative by a run of settle outcomes on a closed order would
        // leave room underneath it for a genuine second charge.
        expect(chargesInFlight, `${where}: charges in flight`).toBeGreaterThanOrEqual(0);
        expect(chargesInFlight, `${where}: charges in flight`).toBeLessThanOrEqual(1);
        expect(goodsReleased, `${where}: the goods went out twice`).toBeLessThanOrEqual(1);
        expect(receipts, `${where}: two receipts for one order`).toBeLessThanOrEqual(1);
      }

      // A floor under the loop: a machine that refused everything would sail
      // through every check above.
      expect(accepted, `seed ${seed}`).toBeGreaterThan(3);
    });
  }

  it("actually reaches the effects those checks are written about", () => {
    // The counters above are worth nothing if the walk never produces the
    // effects they count. Measured over the same seeds and the same lengths as
    // the checks themselves, so this number is the one they ran against.
    const reachedAcrossSeeds = new Set<string>();
    let sawAChargeInFlight = 0;

    for (const seed of seeds) {
      const walked = takeAWalk(seed, 200);
      let inFlight = 0;
      for (const step of walked.trace) {
        for (const kind of step.effects) {
          reachedAcrossSeeds.add(kind);
          if (kind === "execute_payment") inFlight += 1;
        }
        if (step.event === "payment_settled" || step.event === "payment_settle_failed") {
          inFlight = Math.max(inFlight - 1, 0);
        }
        if (inFlight > 0) sawAChargeInFlight += 1;
      }
    }

    for (const kind of EFFECTS_WORTH_REACHING) {
      expect(reachedAcrossSeeds, `the walk never produced ${kind}`).toContain(kind);
    }
    expect(sawAChargeInFlight, "the walk never held a charge in flight").toBeGreaterThan(0);
  });

  it("lets time pass, which is half of what the machine does", () => {
    // A generator steered toward events that move an order will resolve every
    // wait the instant it can, and then no clock in the machine is ever
    // reached. The money assertions above ran over four hundred and sixty
    // accepted steps without a single accepted expiry among them, and the
    // double-charge they guard was only reachable through one.
    const takenFrom = new Map<string, number>();

    for (const seed of seeds) {
      let order = createOrder({
        id: `ord_walk_${seed}`,
        at: WALK_STARTS_AT,
        mode: modeOf("async"),
        policy: POLICY,
        priceCheck: "merchant",
        cardPrice: PRICE,
        test: false,
        selling: "open",
      });
      if (!order.ok) continue;
      let current = order.order;
      let at = WALK_STARTS_AT;
      const next = generator(seed);
      for (let step = 0; step < 200; step += 1) {
        at = tick(next, at);
        const event = anEvent(next, current, at);
        const result = transition(current, event);
        if (!result.ok) continue;
        if (event.kind === "deadline_expired") {
          takenFrom.set(event.deadline, (takenFrom.get(event.deadline) ?? 0) + 1);
        }
        current = result.order;
      }
      order = { ok: true, order: current, effects: [] };
    }

    expect(
      [...takenFrom.keys()].sort().length,
      `expiries taken: ${[...takenFrom]}`,
    ).toBeGreaterThan(2);
  });

  it("produces the very same walk from the very same seed", () => {
    // Determinism is not a nicety here: an order is replayed from its events
    // when the gateway restarts, and a machine that answered differently on
    // the replay would hand a buyer a different outcome than the one he saw.
    const first = takeAWalk(20_260_826, 120);
    const second = takeAWalk(20_260_826, 120);

    expect(second.trace).toStrictEqual(first.trace);
    expect(second.order).toStrictEqual(first.order);
  });

  it("produces different walks from different seeds", () => {
    // The negative control for the test above: if every seed produced the same
    // walk, "the same seed gives the same walk" would be proving nothing.
    const one = takeAWalk(1, 120);
    const other = takeAWalk(42, 120);

    expect(other.trace).not.toStrictEqual(one.trace);
  });

  it("answers the same question the same way twice in a row", () => {
    const { order } = takeAWalk(7, 30);
    const event: OrderEvent = { kind: "deliver_called", at: 900_000 };

    expect(transition(order, event)).toStrictEqual(transition(order, event));
  });

  it("visits every state of the machine for the walk to mean anything", () => {
    // A walk that never left `created` would pass every check above while
    // testing nothing at all. A single order's life is short — most of these
    // walks fall into a closed state early — so the coverage is counted over
    // two hundred orders rather than over one.
    const visited = new Set<string>();
    for (let seed = 1; seed <= 400; seed += 1) {
      const walked = takeAWalk(seed, 200);
      for (const step of walked.trace) {
        visited.add(step.after.split("/")[0] ?? "");
      }
      expect(moneyInvariantViolations(walked.order), `seed ${seed}`).toStrictEqual([]);
    }

    expect([...visited].sort()).toStrictEqual([...ORDER_STATES].sort());
  });
});
