-- A key says what it was made for, and the keys a cabinet holds say so.
--
-- Until now every key was the same kind of thing, and the key a cabinet calls
-- the gateway with sat in the merchant's own list of keys with no button beside
-- it: a row they never made, cannot revoke and have no reason to know about.
-- The column is what tells the two apart, and everything that follows from it —
-- which list a key appears in, which calls can reach it — reads this and not a
-- label.
--
-- Hand-written rather than left as drizzle-kit generated it, for the reason
-- 0003 was: the generated form adds a NOT NULL column with no default, and
-- Postgres refuses that on a table with rows in it. The default is given for
-- the length of the backfill and then taken away again, so that the column
-- matches the schema the code declares — and so that an insert which forgets to
-- say what a key is for is refused rather than quietly making one more key of
-- the merchant's own.
--
-- Every key that already exists is one of the merchant's own except the ones
-- registration made, and the backfill finds those by two facts at once.
--
-- The first is the label, which is the sentence one line of code has ever
-- written and which was never offered to anybody or shown on a screen. The
-- second is the instant: registering writes the merchant and its key in one
-- transaction from one timestamp, so a registration key carries its merchant's
-- own creation time to the microsecond, and a key the merchant issued later —
-- by a different call, at a different moment — cannot. Either fact alone is a
-- guess; a merchant would have to have typed our internal sentence verbatim
-- *and* have done it in the instant their merchant row was written, which no
-- call on this surface makes possible.
--
-- What it would get wrong is worth naming, because it is not the dangerous
-- direction. On a deployment whose registration had stopped writing the two
-- rows together, this marks nothing: cabinet keys would then stay in merchants'
-- lists, which is the state this change exists to leave — visible and wrong,
-- rather than a merchant's own key silently taken out of their hands.
--
-- And it is one-time because from this change on the fact lives in the column.
-- Nothing after this reads a label to decide anything: keys are written with
-- their purpose, and the label goes back to being what it always claimed to be,
-- a word for a person to read.
ALTER TABLE "merchant_keys" ADD COLUMN "purpose" text DEFAULT 'merchant_code' NOT NULL;--> statement-breakpoint
UPDATE "merchant_keys" AS k SET "purpose" = 'cabinet' FROM "merchants" AS m WHERE k."merchant_id" = m."id" AND k."label" = 'the key this merchant registered with' AND k."created_at" = m."created_at";--> statement-breakpoint
ALTER TABLE "merchant_keys" ALTER COLUMN "purpose" DROP DEFAULT;
